##Messages
status = "Status"
success = "Success"
data = "Data"
inventoryNotFound = "Inventory Not Found with this ID"
access_token = "access_token"
token_type = "token_type"
bearer = "Bearer"
user_not_verified = "User could not verify"
internal = "Internal Failed"
authentication_failed = "Authentication Failed"
length = "Length"
user_not_verified = "User could not be verified"
username = "username"
uid = "id"